### PR TITLE
Add 'bb help <command>'

### PR DESCRIPTION
**Pull request by AstralSorceress**
This adds the ability to get the usage for a command through the help command instead of just `bb command -h`.

### CODE REVIEW

**Comment by joeljk13** [comment]
Check your spacing again - I'm detecting spaces where there should be tabs.

**Comment by AstralSorcerer** [comment]
Sorry.  Fixed it.

**Comment by joeljk13** [comment]
There's a bunch of commented out code lines - is there a reason for those? At a glance it looks like they should just be removed.

**Comment by AstralSorcerer** [comment]
Two of them are cases for commands that don't currently have help functions.  I left them in in case help for those commands was added later.  The other comments out a return statement that is innefective after the ```exit 1``` in the ```usage_balance``` function, which is there to match the other ```usage_``` functions.  I didn't know if there was anything special with that particular return statement, so I left it as a comment.

**Comment by clehner** [comment]
Rebased onto master, merged in 4a89768d4b41de55927ac2161e5daa553257fe85

**Pull request closed without merging**
